import { describe, expect, it } from 'vitest';
import { getClashRoyaleDeckLink, parseClashRoyaleDeckLink } from '../src/utils/deckLink';
import { CARDS, CARDS_BY_KEY } from '../src/data/cards';
import { createEmptyDeck, createEmptyDuelDeckSet, validateImportedDeck } from '../src/state/deckUtils';
import type { Deck } from '../src/types/deck';

function deckWith(keys: string[]): Deck {
  const deck = createEmptyDeck('Test');
  keys.forEach((k, i) => {
    deck.slots[i] = k;
  });
  return deck;
}

describe('getClashRoyaleDeckLink', () => {
  it('returns null for an empty deck', () => {
    expect(getClashRoyaleDeckLink(createEmptyDeck('Empty'))).toBeNull();
  });

  it('returns null for a partially filled deck', () => {
    const deck = deckWith(CARDS.slice(0, 5).map((c) => c.key));
    expect(getClashRoyaleDeckLink(deck)).toBeNull();
  });

  it('returns null when a slot holds an unknown card key', () => {
    const keys = CARDS.slice(0, 8).map((c) => c.key);
    keys[3] = 'not-a-real-card';
    expect(getClashRoyaleDeckLink(deckWith(keys))).toBeNull();
  });

  it('builds the official copyDeck link for a full deck', () => {
    const cards = CARDS.slice(0, 8);
    const link = getClashRoyaleDeckLink(deckWith(cards.map((c) => c.key)));
    const expectedIds = cards.map((c) => c.id).join(';');
    expect(link).toBe(
      `https://link.clashroyale.com/en/?clashroyale://copyDeck?deck=${expectedIds}&l=Royals&tt=159000000`,
    );
  });

  it('preserves slot order in the link', () => {
    const keys = ['knight', 'archers', 'goblins', 'giant', 'fireball', 'musketeer', 'mini-pekka', 'zap'];
    const available = keys.filter((k) => CARDS_BY_KEY.has(k));
    expect(available).toHaveLength(8);
    const link = getClashRoyaleDeckLink(deckWith(keys));
    const ids = keys.map((k) => CARDS_BY_KEY.get(k)!.id);
    expect(link).toContain(`deck=${ids.join(';')}`);
  });
});

describe('parseClashRoyaleDeckLink', () => {
  const cards = CARDS.slice(0, 8);
  const ids = cards.map((c) => c.id).join(';');

  it('round-trips a link generated by getClashRoyaleDeckLink', () => {
    const link = getClashRoyaleDeckLink(deckWith(cards.map((c) => c.key)))!;
    expect(parseClashRoyaleDeckLink(link)).toEqual(cards.map((c) => c.key));
  });

  it('accepts a URL-encoded link', () => {
    const encoded = `https://link.clashroyale.com/en/?clashroyale%3A%2F%2FcopyDeck%3Fdeck%3D${ids.replace(/;/g, '%3B')}%26l%3DRoyals`;
    expect(parseClashRoyaleDeckLink(encoded)).toEqual(cards.map((c) => c.key));
  });

  it('accepts the bare clashroyale:// URI with surrounding whitespace', () => {
    expect(parseClashRoyaleDeckLink(`  clashroyale://copyDeck?deck=${ids}&l=Royals  `)).toEqual(
      cards.map((c) => c.key),
    );
  });

  it('rejects plain text, short decks and unknown ids', () => {
    expect(parseClashRoyaleDeckLink('hello world')).toBeNull();
    expect(parseClashRoyaleDeckLink('https://example.com')).toBeNull();
    expect(parseClashRoyaleDeckLink(`deck=${cards.slice(0, 5).map((c) => c.id).join(';')}`)).toBeNull();
    expect(parseClashRoyaleDeckLink('deck=1;2;3;4;5;6;7;8')).toBeNull();
  });
});

describe('validateImportedDeck', () => {
  const keys8 = CARDS.filter((c) => !c.isChampion).slice(0, 8).map((c) => c.key);
  const champion = CARDS.find((c) => c.isChampion)!;

  it('accepts 8 unique known cards', () => {
    const result = validateImportedDeck(keys8, CARDS_BY_KEY);
    expect('slots' in result && result.slots).toEqual(keys8);
  });

  it('moves a champion into the hero slot (index 1)', () => {
    const keys = [...keys8.slice(0, 7), champion.key]; // champion last
    const result = validateImportedDeck(keys, CARDS_BY_KEY);
    if (!('slots' in result)) throw new Error(result.error);
    expect(result.slots[1]).toBe(champion.key);
    expect(new Set(result.slots).size).toBe(8);
  });

  it('rejects in-deck duplicates', () => {
    const dup = [...keys8.slice(0, 7), keys8[0]];
    expect('error' in validateImportedDeck(dup, CARDS_BY_KEY)).toBe(true);
  });

  it('accepts two champions and seats them in the Hero and Wild slots', () => {
    const champs = CARDS.filter((c) => c.isChampion).slice(0, 2).map((c) => c.key);
    const twoChamps = [...keys8.slice(0, 6), ...champs]; // both champions at the end
    const result = validateImportedDeck(twoChamps, CARDS_BY_KEY);
    if (!('slots' in result)) throw new Error(result.error);
    expect([result.slots[1], result.slots[2]].sort()).toEqual([...champs].sort());
    expect(new Set(result.slots).size).toBe(8);
  });

  it('rejects a deck with three champions', () => {
    const champs = CARDS.filter((c) => c.isChampion).slice(0, 3).map((c) => c.key);
    const threeChamps = [...keys8.slice(0, 5), ...champs];
    expect('error' in validateImportedDeck(threeChamps, CARDS_BY_KEY)).toBe(true);
  });

  it('allows cards already used in other decks (shown as duplicates in the UI)', () => {
    // Import no longer blocks cross-deck duplicates — they render B&W instead.
    const set = createEmptyDuelDeckSet('S');
    set.decks[1].slots[0] = keys8[0];
    const result = validateImportedDeck(keys8, CARDS_BY_KEY);
    expect('slots' in result).toBe(true);
  });
});
