import { readdirSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';
import { getClashRoyaleDeckLink, getDeckLinkFromKeys, parseClashRoyaleDeckLink } from '../src/utils/deckLink';
import { CARDS, CARDS_BY_KEY } from '../src/data/cards';
import { createEmptyDeck, createEmptyDuelDeckSet, validateImportedDeck } from '../src/state/deckUtils';
import type { Deck } from '../src/types/deck';

function deckWith(keys: string[]): Deck {
  const deck = createEmptyDeck('Test');
  keys.forEach((k, i) => {
    deck.slots[i] = k;
  });
  return deck;
}

describe('getClashRoyaleDeckLink', () => {
  it('returns null for an empty deck', () => {
    expect(getClashRoyaleDeckLink(createEmptyDeck('Empty'))).toBeNull();
  });

  it('returns null for a partially filled deck', () => {
    const deck = deckWith(CARDS.slice(0, 5).map((c) => c.key));
    expect(getClashRoyaleDeckLink(deck)).toBeNull();
  });

  it('returns null when a slot holds an unknown card key', () => {
    const keys = CARDS.slice(0, 8).map((c) => c.key);
    keys[3] = 'not-a-real-card';
    expect(getClashRoyaleDeckLink(deckWith(keys))).toBeNull();
  });

  it('builds the official copyDeck link for a full deck', () => {
    const cards = CARDS.slice(0, 8);
    const link = getClashRoyaleDeckLink(deckWith(cards.map((c) => c.key)));
    const expectedIds = cards.map((c) => c.id).join(';');
    expect(link).toBe(
      `https://link.clashroyale.com/en/?clashroyale://copyDeck?deck=${expectedIds}&l=Royals&tt=159000000`,
    );
  });

  it('preserves slot order in the link', () => {
    const keys = ['knight', 'archers', 'goblins', 'giant', 'fireball', 'musketeer', 'mini-pekka', 'zap'];
    const available = keys.filter((k) => CARDS_BY_KEY.has(k));
    expect(available).toHaveLength(8);
    const link = getClashRoyaleDeckLink(deckWith(keys));
    const ids = keys.map((k) => CARDS_BY_KEY.get(k)!.id);
    expect(link).toContain(`deck=${ids.join(';')}`);
  });
});

describe('parseClashRoyaleDeckLink', () => {
  const cards = CARDS.slice(0, 8);
  const ids = cards.map((c) => c.id).join(';');

  it('round-trips a link generated by getClashRoyaleDeckLink', () => {
    const link = getClashRoyaleDeckLink(deckWith(cards.map((c) => c.key)))!;
    expect(parseClashRoyaleDeckLink(link)).toEqual(cards.map((c) => c.key));
  });

  it('accepts a URL-encoded link', () => {
    const encoded = `https://link.clashroyale.com/en/?clashroyale%3A%2F%2FcopyDeck%3Fdeck%3D${ids.replace(/;/g, '%3B')}%26l%3DRoyals`;
    expect(parseClashRoyaleDeckLink(encoded)).toEqual(cards.map((c) => c.key));
  });

  it('accepts the bare clashroyale:// URI with surrounding whitespace', () => {
    expect(parseClashRoyaleDeckLink(`  clashroyale://copyDeck?deck=${ids}&l=Royals  `)).toEqual(
      cards.map((c) => c.key),
    );
  });

  it('rejects plain text, short decks and unknown ids', () => {
    expect(parseClashRoyaleDeckLink('hello world')).toBeNull();
    expect(parseClashRoyaleDeckLink('https://example.com')).toBeNull();
    expect(parseClashRoyaleDeckLink(`deck=${cards.slice(0, 5).map((c) => c.id).join(';')}`)).toBeNull();
    expect(parseClashRoyaleDeckLink('deck=1;2;3;4;5;6;7;8')).toBeNull();
  });
});

describe('validateImportedDeck', () => {
  const keys8 = CARDS.filter((c) => !c.isChampion).slice(0, 8).map((c) => c.key);
  const champion = CARDS.find((c) => c.isChampion)!;

  it('accepts 8 unique known cards', () => {
    const result = validateImportedDeck(keys8, CARDS_BY_KEY);
    expect('slots' in result && result.slots).toEqual(keys8);
  });

  it('moves a champion into the hero slot (index 1)', () => {
    const keys = [...keys8.slice(0, 7), champion.key]; // champion last
    const result = validateImportedDeck(keys, CARDS_BY_KEY);
    if (!('slots' in result)) throw new Error(result.error);
    expect(result.slots[1]).toBe(champion.key);
    expect(new Set(result.slots).size).toBe(8);
  });

  it('rejects in-deck duplicates', () => {
    const dup = [...keys8.slice(0, 7), keys8[0]];
    expect('error' in validateImportedDeck(dup, CARDS_BY_KEY)).toBe(true);
  });

  it('accepts two champions and seats them in the Hero and Wild slots', () => {
    const champs = CARDS.filter((c) => c.isChampion).slice(0, 2).map((c) => c.key);
    const twoChamps = [...keys8.slice(0, 6), ...champs]; // both champions at the end
    const result = validateImportedDeck(twoChamps, CARDS_BY_KEY);
    if (!('slots' in result)) throw new Error(result.error);
    expect([result.slots[1], result.slots[2]].sort()).toEqual([...champs].sort());
    expect(new Set(result.slots).size).toBe(8);
  });

  it('rejects a deck with three champions', () => {
    const champs = CARDS.filter((c) => c.isChampion).slice(0, 3).map((c) => c.key);
    const threeChamps = [...keys8.slice(0, 5), ...champs];
    expect('error' in validateImportedDeck(threeChamps, CARDS_BY_KEY)).toBe(true);
  });

  it('allows cards already used in other decks (shown as duplicates in the UI)', () => {
    // Import no longer blocks cross-deck duplicates — they render B&W instead.
    const set = createEmptyDuelDeckSet('S');
    set.decks[1].slots[0] = keys8[0];
    const result = validateImportedDeck(keys8, CARDS_BY_KEY);
    expect('slots' in result).toBe(true);
  });
});

/* THE TWO CARDS ADDED FOR SEASON 87, PINNED.
 *
 * The card `id` is the one value here that could not be confirmed against a
 * public source. Every fact around it was — Rare, 4 elixir, a Troop, a flying
 * win condition that targets buildings — but no card database on the open web
 * had published the numeric id yet, and the upstream snapshot this project
 * refreshes from (`royaleapi.github.io/cr-api-data`) is still on 120 cards.
 * 26000107 came from the account holder and is consistent with the sequence
 * (Ronin, the previous troop, is 26000106).
 *
 * That matters because the id is not decoration: `deckLink.ts` builds the
 * official copyDeck deep link out of it and parses incoming links by it, so a
 * wrong number means "Open in Game" hands the game a card it does not
 * recognise. Pinning it here means a future correction is a one-line change
 * with a test that says what it is for, rather than a silent mystery about why
 * one card breaks a deck link.
 */
describe('season 87 cards', () => {
  it('Minion Giant is in the set with the researched values', () => {
    const c = CARDS_BY_KEY.get('minion-giant');
    expect(c).toBeTruthy();
    expect({
      elixir: c!.elixir, rarity: c!.rarity, type: c!.type,
      id: c!.id, win: c!.isWinCondition,
    }).toEqual({ elixir: 4, rarity: 'Rare', type: 'Troop', id: 26000107, win: true });
  });

  it('Minion Giant survives a deck-link roundtrip', () => {
    const keys = ['minion-giant', 'knight', 'archers', 'arrows',
                  'fireball', 'giant', 'musketeer', 'zap'];
    const link = getDeckLinkFromKeys(keys);
    expect(link).toContain('26000107');
    expect(parseClashRoyaleDeckLink(link!)).toEqual(keys);
  });

  /* The Hero Ice Wizard is NOT a new card — it is a hero form of the Ice
     Wizard that already existed, so it is a flag plus a file in `heroes/`. */
  it('Ice Wizard can now be brought as a hero', () => {
    expect(CARDS_BY_KEY.get('ice-wizard')!.canBeHero).toBe(true);
  });
});

/*
 * 2026-10-06: two more FORMS, no new card. Hero Electro Wizard and Evolution
 * Electro Giant are each a flag in `cardMeta.json` plus one file of art, and
 * the copyDeck link does not change for either — a form is a slot position,
 * not an id.
 *
 * Neither card gained its SECOND form, which is the part worth pinning: the
 * Wild-slot picker offers a choice only for a card that owns both, and that
 * list is four cards the builder, the server and the docs all name.
 */
describe('october 2026 forms', () => {
  it('Electro Wizard can be brought as a hero, and only as a hero', () => {
    const c = CARDS_BY_KEY.get('electro-wizard')!;
    expect({ hero: c.canBeHero, evo: c.canEvolve }).toEqual({ hero: true, evo: false });
  });

  it('Electro Giant can evolve, and only evolve', () => {
    const c = CARDS_BY_KEY.get('electro-giant')!;
    expect({ hero: c.canBeHero, evo: c.canEvolve }).toEqual({ hero: false, evo: true });
  });

  it('the cards with BOTH forms are still exactly the four the Wild picker knows', () => {
    const both = CARDS.filter((c) => c.canEvolve && c.canBeHero).map((c) => c.key).sort();
    expect(both).toEqual(['knight', 'musketeer', 'valkyrie', 'wizard']);
  });

  /* A flag without its file is a broken image on a live screen, and nothing
     else fails: not the build, not the typecheck — `public/` is copied, never
     imported. So the two lists are held equal here, in BOTH directions; art
     nobody can reach is the other half of the same drift. */
  it.each([
    ['evolutions', (k: string) => !!CARDS_BY_KEY.get(k)?.canEvolve],
    ['heroes', (k: string) => !!CARDS_BY_KEY.get(k)?.canBeHero],
  ] as const)('every flagged card has art in %s/, and every file there has a flag', (dir, flagged) => {
    const files = readdirSync(join(process.cwd(), 'public', 'assets', dir))
      .filter((f) => f.endsWith('.webp'))
      .map((f) => f.slice(0, -'.webp'.length))
      .sort();
    const want = CARDS.map((c) => c.key).filter(flagged).sort();
    expect(files).toEqual(want);
  });
});
